name: iim_shillong_community
description: IIM Shillong community timetable POC — institute login, Excel parse, electives, reminders.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.1.0
  firebase_analytics: ^12.0.4
  excel: ^4.0.6
  flutter_local_notifications: ^19.5.0
  file_picker: ^10.3.3
  timezone: ^0.10.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  path: ^1.9.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_timetable.xlsx
